### ISSUE TITLE
Peer-to-Peer Review

### ISSUE THREAD

**Issue by nikoescobal** [somoye123/New-York-Times-Article-Page#2]
One reviewer commented that the title of the project is named incorrectly as the previous project.

One reviewer commented about the font size for the footer to be changed to responsive, since other screens may display the content differently.

One reviewer commented that the login button is too near the border. Might be because of the screen being small, but adding some margin is suggested. It is also important to add the "Get Started" section as well to the readME file.

One reviewer commented that a table of content would be really helpful to improve the readability of the CSS code. Another reviewer commented that the table of contents is not necessarily needed, as this is an issue that has no clear side.

One reviewer commented that there was a typo with one of the links (line 102).

The presenter added that there was a contradiction with Github actions and footer styling. He also asked the team how to disable stickler, as it presented some issues. One reviewer guided him through the process on how to fix.

**Comment by somoye123** [comment]
Thanks 
All issues as been addressed and fixed
